function(deploy_cuda_dependencies TARGET_NAME COMPONENTS)
    set(TARGET_DEPENDENCIES_COMMON ${COMPONENTS})
    set(TARGET_DEPENDENCIES_DEBUG "")
    set(TARGET_DEPENDENCIES_RELEASE "")
    list(TRANSFORM TARGET_DEPENDENCIES_COMMON APPEND "64_${CUDA_VERSION_MAJOR}")
    list(TRANSFORM TARGET_DEPENDENCIES_COMMON REPLACE "cudart64_${CUDA_VERSION_MAJOR}"
                                                      "cudart64_${CUDA_VERSION_MAJOR}0")
    # cufft is currently at version 10
    list(TRANSFORM TARGET_DEPENDENCIES_COMMON REPLACE "cufft64_${CUDA_VERSION_MAJOR}" "cufft64_10")
    list(TRANSFORM TARGET_DEPENDENCIES_COMMON REPLACE "curand64_${CUDA_VERSION_MAJOR}" "curand64_10")
    list(TRANSFORM TARGET_DEPENDENCIES_COMMON APPEND ".dll")
    list(TRANSFORM TARGET_DEPENDENCIES_COMMON PREPEND "${CUDAToolkit_BIN_DIR}/")

    deploy_dependencies(${TARGET_NAME} "${TARGET_DEPENDENCIES_COMMON}" "${TARGET_DEPENDENCIES_DEBUG}"
                        "${TARGET_DEPENDENCIES_RELEASE}")
endfunction()
